### ISSUE TITLE
How to mint NFT in Magic Eden by web3 or rpc

### ISSUE THREAD

**Issue by needman0914** [DavidReider/MagicEdenFloorTrack#10]
Thanks for your project.
I want to mint NFT in Magic Eden by web3 or rpc.
As you know we can mint NFT by web3 in Candy Machine.
Like this way, How can i do in Magic Eden?

**Comment by DavidReider** [comment]
Hi @needman0914 !
Thank you for your enquiry. I do not have experience creating NFTs and am not affiliated with Magic Eden, so while I do not directly know the answer to your question, I was able to find something after a quick online search. 

Please refer to [this article](https://www.quicknode.com/guides/web3-sdks/how-to-mint-an-nft-on-solana) and see if this provides the answers you're looking for.

Best Wishes
