### ISSUE TITLE
Limit Requests to Database

### ISSUE THREAD

**Issue by DavidReider** [DavidReider/MagicEdenFloorTrack#12]
Once we start pulling from Supabase, we will want to try to limit requests so that it doesn't have to query the database when someone refreshes the page (since it will only updates hourly). 

Possibly some sort of caching or way to only update the data hourly?

**Comment by WaterlessPiano2** [comment]
How will this benefit the site? Do we have a limit on how many requests can be made to the database or something?

**Comment by DavidReider** [comment]
Hi @WaterlessPiano2 !

I misread their free tier and it looks like we actually do have unlimited API requests to the DB, thanks for questioning me on that.

This likely isn't needed, then!
