### ISSUE TITLE
Magic Eden RPC list

### ISSUE THREAD

**Issue by needman0914** [DavidReider/MagicEdenFloorTrack#14]
Hello.
Thanks for your project.
I wanna know about Magic Eden RPC list.
where can I find Magic Eden RPC list.
I hope your response

**Comment by DavidReider** [comment]
Hi, 

I am not sure what you mean?

Thanks,

**Comment by needman0914** [comment]
You have used magic eden rpc in your code.
like this
```
const apiUrl =
  "https://api-mainnet.magiceden.io/rpc/getAggregatedCollectionMetrics";
```

I wanna know all the list of rpcs of magic eden
Where I can find this?
Thanks

**Comment by DavidReider** [comment]
I got that off of the Magic Eden website. I am not affiliated with them and do not know much more about it than my intended use purposes. Please attempt some looking yourself on their website and Google! 

Thanks!
