### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by DavidReider** [DavidReider/MagicEdenFloorTrack#5]
As I am learning while coding, there is a lot of sloppy code going into the files. 

It will be good to refactor the code to be consistent throughout.

For example, in api.js, some functions are using async/await and then some use .then()...

Additionally, can fix naming conventions, convert all functions to be the same style (arrow functions versus standard function syntax) and any other code cleanup.

**Comment by WaterlessPiano2** [comment]
it looks good to me so far mate :)

**Comment by DavidReider** [comment]
Thanks! There are definitely improvements and consistency practices that could be made but I suppose that might be more important in the future. I'll close this for now and open something else in the future once there is more code :)
