### ISSUE TITLE
[Help Wanted] Supabase Query for homepage table

### ISSUE THREAD

**Issue by DavidReider** [DavidReider/MagicEdenFloorTrack#6]
Need to write an efficient query to Supabase on the [feat-react-revamp](https://github.com/DavidReider/MagicEdenFloorTrack/tree/feat-react-revamp) branch. 

This query should fetch the collection name, the floor price and previous floor price and volume so we can output in the table.

I believe we may need to use an rpc function

**Comment by WaterlessPiano2** [comment]
Hey buddy, I love this repo, and how minimalistic and simple it is. I never used supabase before but can learn easily.

I would like to help you, but I can't access the db without the SUPABASE_KEY. Can you make a dummy table and share the SUPABASE_KEY with me? So I can look in to this.

My email in my Bio :)

**Comment by DavidReider** [comment]
Hi @WaterlessPiano2 ! 

Thank you for the kind words. I hope to keep this something minimalistic/simple to navigate as we build on it!

I have invited you to the Supabase project via Email invite! Let me know if you have any questions!  Supabase has some pretty decent documentation but I am still learning! 

If you'd like, I can assign this issue to you to give a shot at tackling! 

Thanks!

**Comment by WaterlessPiano2** [comment]
Hello, 

I see :) that is a good idea to keep it simple, especially in the early days of the product.

I have received an email invite, but the invite link on the email has localhost:3000 as the base URL then all the auth tokens. Because I am unable to start the project without the API key I am unable to use this URL. I can forward the email to you if you want to have a look.

And yea for sure, assign it to me :)

**Comment by DavidReider** [comment]
Hello! 

I have sent you a follow up email with the access you should need!

Also, assigned to you! If you need anything, please let me know!

**Comment by WaterlessPiano2** [comment]
I got the email and the api seems to be runing now thank you :)

**Comment by DavidReider** [comment]
Closing this issue with PR #9 ! 

Thanks for fulfilling that one!
