### ISSUE TITLE
Unable to push a new branch from main branch

### ISSUE THREAD

**Issue by WaterlessPiano2** [DavidReider/MagicEdenFloorTrack#7]
There seems to be some restrictions on who can push on this repo on git hub. I ensured my github is configured properly on my command line and I am using ssh to contribute with this user account.

Here is the steps I took and the error I get while pushing to this repo

``` 
chad@chad-MS-7C02:~/Desktop/codes/MagicEdenFloorTrack$ git status
On branch main
Your branch is up-to-date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   README.md

no changes added to commit (use "git add" and/or "git commit -a")
chad@chad-MS-7C02:~/Desktop/codes/MagicEdenFloorTrack$ git checkout -b readme
Switched to a new branch 'readme'
chad@chad-MS-7C02:~/Desktop/codes/MagicEdenFloorTrack$  git commit -m 'readme update'
[readme 1c02438] readme update
 1 file changed, 16 insertions(+), 1 deletion(-)
chad@chad-MS-7C02:~/Desktop/codes/MagicEdenFloorTrack$ git push
fatal: The current branch readme has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin readme

chad@chad-MS-7C02:~/Desktop/codes/MagicEdenFloorTrack$     git push --set-upstream origin readme
ERROR: Permission to DavidReider/MagicEdenFloorTrack.git denied to WaterlessPiano2.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
chad@chad-MS-7C02:~/Desktop/codes/MagicEdenFloorTrack$ 

```

**Comment by DavidReider** [comment]
Hi @WaterlessPiano2 !

I've reviewed the settings on the repository and nothing is sticking out that would restrict access.
I've invited you directly to the repository, if you'd like to try again!

I will try to debug this issue more so other contributors don't have to be added to 'direct access', but if you know which setting it may be feel free to let me know! 

Thank you!


Note: I haven't changed any settings from the default initialization of a repository. On a different repo, I've had a user contribute and settings look similar.

**Comment by DavidReider** [comment]
Thinking about this a bit more - I think the proper process would be to fork the repository so that it is added to your profile and then you would push to the forked repo and open a pull request that way. 

https://www.dataschool.io/how-to-contribute-on-github/

I think the issue here is that you were trying to contribute directly to the repository rather than using the fork method from the article above. 

I'm going to revoke the direct access from the previous message. Could we try the method above (fork, push to that, open pull requests that way?)

Thanks!

**Comment by WaterlessPiano2** [comment]
Okay cool, I will give this a go :+1

**Comment by DavidReider** [comment]
Closing this since you were able to fork and create a pull request!
